$$
\phi_{i, j}^{k+1}=\frac{1}{4}\left(\phi_{i-1, j}^{k+1}+\phi_{i, j-1}^{k+1}+\phi_{i+1, j}^{k}+\phi_{i, j+1}^{k}\right)-\frac{1}{4} b_{i, j}
$$

Here, $\phi$ represents the pressure $P_{i,j}$, and 
$$
b_{i,j} = \Delta x^2 \frac{\rho_0}{\Delta t} \left(\frac{\partial u^{**}}{\partial x} +  \frac{\partial v^{**}}{\partial y} \right)_{i,j}
$$

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
%reload_ext autoreload
%aimport poisson_solver
from poisson_solver import SOR_solver

In [5]:
%autoreload 1
from scipy.constants import epsilon_0
rho = 1e-8

"""Mesh parameters"""
N = 100
M = 100
dx = 1./N
dy = 1./M

b = - dx**2 * rho / epsilon_0 * np.ones((N,M))

In [6]:
phi = SOR_solver(b, w=1.5)

In [ ]:
scipy.sparse.diags()

In [71]:
N,M = 3,3
A1 = 4 * np.identity(N*M)
A2 = np

In [72]:
print(A1 + A2)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
